[package]
name = "ios"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bevyedge"
crate-type= ["staticlib"]

[dependencies]
input = { path = "../input" }

env_logger = "0.9.1"

log.workspace = true
