[workspace]
members = [
  "android",
  "input",
  "ios",
  "stdin",
]

[package]
name = "bevy-edge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
bincode = "1.3.3"
console = "0.15.2"
log = "0.4.17"
once_cell = "1.15.0"
bevy_input = { version = "0.8.1", features = ["serialize"] }

[dependencies]
bevy_core = "0.8.1"
bevy_log = { version = "0.8.1", features = ["trace", "tracing-chrome"] }
bevy_app = { version = "0.8.1", default-features = false }
bevy_time = "0.8.1"
bevy_window = "0.8.1"
bevy_winit = { version = "0.8.1", features = ["wayland"] }
bevy_ecs = { version = "0.8.1", default-features = false }
bevy_input.workspace = true

crossbeam = "0.8.2"

bincode.workspace = true
console.workspace = true

[profile.release]
lto = true
